#!/bin/bash
echo "special variables passed through the script are: $@"
echo "the number of arguments passed is: $#"
echo "the name of the script is: $0"
echo "the first argument is: $1"
echo "the second argument is: $2"
echo "the third argument is: $3"
echo "who is running the script: $USER"
echo "the process id of the script is: $$"
echo "the exit status of the last command is: $?"
echo "the last background process id is: $!"
echo "the current shell is: $SHELL"
echo "the current working directory is: $PWD"
echo "the home directory of the user is: $HOME"
echo "the current date and time is: $(date)"
echo "the current time in seconds since epoch is: $(date +%s)"
echo "the current time in seconds since epoch is: $(date +%s.%N)"
